Fix some typos
apple/swift-protobuf pull request #1589
Opened 2024-03-19 19:41 UTC by mrs1669

I found a few typos.
I would be grateful if you could confirm. I hope this helps!

2024-03-19 19:54 UTC, thomasvl reviewed
Thanks!

The .pb.swift files need the fixes in the .proto files in the Protos/ sub directories so they won't get lost the next time we regenerated.

You'll also need to fix/update the copies in the Reference/ directory as the CI will then catch them not matching once the .proto files are updated.

2024-03-19 19:54 UTC, thomasvl commented on CompileTests/MultiModule/Sources/ModuleA/a.pb.swift
> +// Swift Extensions on the extended Messages to add easy access to the declared
This should be fixed in the a.proto file otherwise it will get lose on the next generation.

2024-03-19 19:54 UTC, thomasvl commented on FuzzTesting/Sources/FuzzCommon/fuzz_testing.pb.swift
> +// Swift Extensions on the extended Messages to add easy access to the declared
Same, fix the .proto fuzz_testing.proto file.

2024-03-20 00:28 UTC, mrs1669 commented
Thanks for review!
Please tell me the following point that I do not understand.

> The .pb.swift files need the fixes in the .proto files in the Protos/ sub directories so they won't get lost the next time we regenerated.

I am aware that there is no modification to the .proto file since the PR is a modification of the comment out in the .pb.swift file, is this correct?
It is my understanding that [this diff](https://github.com/apple/swift-protobuf/pull/1589/files#diff-579304a80fa4b82b64c568287087a932f09d2fb7d8c682111405bc3d681cb70bR159) fixes all "exteneded" in the repository when it is regenerated.

2024-03-20 00:30 UTC, mrs1669 commented
> You'll also need to fix/update the copies in the Reference/ directory as the CI will then catch them not matching once the .proto files are updated.

https://github.com/apple/swift-protobuf/pull/1589/commits/edbc683a1499fe98e74f6c140b5e10ef8f7a78c1
This commit replaces all "extended" with "extended" in repositories, including Reference/ directory. Please let me know if I'm wrong about how to respond!

2024-03-20 00:37 UTC, tbkka commented
You should never directly edit any `.pb.swift` file or anything under `Reference`.  All such files are created from other files.  The original files should be edited instead and we will separately re-create those files to update their contents.

2024-03-20 01:09 UTC, mrs1669 commented
Thank you, I understand.
I'll revert all `.pb.swift` file and `Reference/` directory diff.

2024-03-20 13:16 UTC, thomasvl approved these changes
Thank you!

2024-03-20 13:28 UTC, thomasvl requested changes
Since one of the changes is in the generated text for files, you'll need to do a `make regenerate reference` to get things updated. That requires you have `protoc` on your path.

2024-03-24 06:45 UTC, mrs1669 commented
@thomasvl 
I built protoc environment and also committed the diff generated by `make regenerate reference` command. 
please run CI and check it 🙇

2024-03-25 12:26 UTC, thomasvl approved these changes
Thank you again, looks good to go now.

2024-03-25 12:27 UTC, merged