Use repeat instead of break label for utf8ToString
apple/swift-protobuf pull request #1656
Opened 2024-05-18 19:52 UTC by kyulee-com

This update doesn't change functionality, but improves the (LLVM) loop optimizer. The old break label created a complex nested loop, which could cause errors and was inefficient. Now, we're using a repeat command with a boolean check to make the loop simpler and more efficient.

2024-05-19 01:03 UTC, kyulee-com commented
@thomasvl @gjcairo I'm not sure if this is a right process to request a PR here. But found this code was problematic in our code base in a certain combination of opts, and the suggested change produced much cleaner code.  Let me know how to test this code.

2024-05-20 14:15 UTC, thomasvl commented
If there compiler does better with the change, I think there are a few other loops in the library that maybe should be tweaked.

2024-05-20 14:15 UTC, Lukasa requested changes
Gus's callout here is great, the logic here has completely been inverted.

I'm also curious about the bad codegen and the LLVM miscompile. Do you have an llvm issue for the latter, and can you show us what you meant for the former? The code here seems likely to compile absolutely trivially, the labelled break should be almost irrelevant from LLVM's perspective.

2024-05-22 23:52 UTC, kyulee-com commented
Thanks all for looking at this issue. It seems my first attempt was entirely off, but after further investigation, I've come up with another workaround. I've reported a bug in LLVM, which you can find at https://github.com/llvm/llvm-project/issues/93110. I don't intend to upstream this workaround in the source as it seems too disruptive, but perhaps use this workaround in our downstream. Anyhow, I'm sharing this with a comment for reference.

2024-05-29 13:43 UTC, Lukasa commented
Thanks so much for your diligent work root-causing this, and for providing a workaround. As we only see a severe issue in thin-lto mode I'm ok with us calling the current code good, and waiting for Swift to fix the apparent miscompile issue. I've flagged this for the Swift team.

2024-05-29 14:15 UTC, closed without merging